name: matrix
on:
  push:
jobs:
  simple:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        foo:
          - foo-1
          - foo-2
        bar:
          - bar-1
          - bar-2
    steps:
      - run: |
          echo "${{ matrix.foo }} - ${{ matrix.bar }}"
  include:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - 
            foo: foo-1
            bar: bar-1
          -
            foo: foo-2
            bar: bar-2
    steps:
      - run: |
          echo "${{ matrix.foo }} - ${{ matrix.bar }}"
